import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import axios from 'axios';

const Home: NextPage = () => {
  const makePaymentThroughAPI = async () => {
    const response = await axios
      .get('/api/example-using-api-req')
      .catch((err) => {
        console.error(err);
      });

    if (response?.data) {
      document.open();
      document.write(response?.data);
      document.close();
    }
  };

  const makePaymentUsingHiddenForm = async () => {
    const response = await axios
      .get('/api/example-using-hidden-form')
      .catch((err) => {
        console.error(err);
      });

    if (response?.data) {
      document.open();
      document.write(response?.data);
      document.close();
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>next senangpay example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ marginBottom: '10px' }}>
          <button onClick={() => makePaymentThroughAPI()}>
            Pay here (api request)
          </button>
        </div>
        <div>
          <button onClick={() => makePaymentUsingHiddenForm()}>
            Pay here (hidden form)
          </button>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
